# Generated by Django 4.1.5 on 2023-02-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ImageField(upload_to='')),
                ('adresse', models.CharField(max_length=200)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menage.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
