# Generated by Django 4.1.5 on 2023-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menage', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='types',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
